# Generated by Django 5.0.1 on 2025-04-12 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikelblog_delete_artikel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtikelBlog',
            new_name='Artikel',
        ),
    ]
