# Generated by Django 5.0.1 on 2025-06-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
